import { db } from '@/db';
import { observations } from '@/db/schema';

async function main() {
    const sampleObservations = [
        {
            childId: 4,
            date: '2025-09-01',
            time: '09:30',
            domain: '사회',
            tags: JSON.stringify(['친구관계', '협력활동', '감정표현']),
            summary: '친구들과 함께 블록 쌓기 활동에서 적극적으로 참여하며 자신의 의견을 표현함',
            detail: '자유놀이 시간에 친구 3명과 함께 큰 성을 만드는 활동을 하였습니다. 처음에는 혼자 작은 집을 만들려고 했으나, 친구들이 함께 하자고 제안하자 흔쾌히 동의했습니다. 활동 중 "여기에 문을 만들어야 해!"라고 적극적으로 의견을 제시하였고, 친구가 다른 의견을 말하자 "그것도 좋은 생각이야!"라고 긍정적으로 반응했습니다.',
            media: JSON.stringify([]),
            author: '이슬반_김교사',
            followUps: JSON.stringify(['사회성 발달 관찰 지속', '협력활동 기회 확대']),
            linkedToReport: false,
            createdAt: new Date('2025-09-01T09:45:00').toISOString(),
            updatedAt: new Date('2025-09-01T09:45:00').toISOString(),
        },
        {
            childId: 4,
            date: '2025-09-03',
            time: '10:15',
            domain: '신체',
            tags: JSON.stringify(['대근육발달', '균형감각', '운동능력']),
            summary: '평균대 위에서 안정적으로 걸으며 양팔을 벌려 균형을 잡는 모습 관찰',
            detail: '신체활동 시간에 평균대 건너기를 하였습니다. 처음에는 교사의 손을 잡고 천천히 걸었으나, 두 번째부터는 혼자서도 안정적으로 건널 수 있었습니다. 균형을 잃을 뻔할 때 양팔을 넓게 벌려 중심을 잡는 모습이 인상적이었습니다. 다른 친구들이 박수를 치자 뿌듯해하며 "나 혼자서도 할 수 있어!"라고 자신감 있게 말했습니다.',
            media: JSON.stringify([]),
            author: '이슬반_김교사',
            followUps: JSON.stringify(['평균대 난이도 점진적 증가', '다양한 균형놀이 제공']),
            linkedToReport: false,
            createdAt: new Date('2025-09-03T10:30:00').toISOString(),
            updatedAt: new Date('2025-09-03T10:30:00').toISOString(),
        },
        {
            childId: 4,
            date: '2025-09-05',
            time: '11:00',
            domain: '의사소통',
            tags: JSON.stringify(['언어표현', '어휘력', '말하기']),
            summary: '동화책을 읽고 자신만의 이야기로 창의적으로 재구성하여 발표함',
            detail: '동화 읽기 시간에 "아기돼지 삼형제" 이야기를 들은 후, 자신만의 버전으로 이야기를 만들어 발표했습니다. "네 번째 돼지가 있었는데, 그 돼지는 유리로 집을 만들었어요. 늑대가 와서 후~ 불었는데 안 무너졌어요!"라고 상상력을 발휘했습니다. 친구들이 재미있어하자 더욱 신이 나서 몸짓과 표정을 과장되게 표현하며 이야기했습니다.',
            media: JSON.stringify([]),
            author: '이슬반_박교사',
            followUps: JSON.stringify(['창의적 언어표현 격려', '발표 기회 확대']),
            linkedToReport: false,
            createdAt: new Date('2025-09-05T11:15:00').toISOString(),
            updatedAt: new Date('2025-09-05T11:15:00').toISOString(),
        },
        {
            childId: 4,
            date: '2025-09-08',
            time: '14:20',
            domain: '예술',
            tags: JSON.stringify(['미술활동', '창의성', '색채감각']),
            summary: '가을 단풍잎을 모티브로 한 콜라주 작품에서 독창적인 색감 조합을 보여줌',
            detail: '미술활동 시간에 단풍잎 콜라주를 만들었습니다. 일반적으로 빨강, 노랑, 주황색을 많이 사용하는데, 이 아동은 보라색과 파란색을 주요 색상으로 선택했습니다. "진짜 단풍잎은 이런 색이 아니지만, 내가 상상하는 예쁜 단풍잎이야"라고 설명했습니다. 작품 완성 후 친구들에게 자신의 작품을 소개하며 각 부분에 담긴 의미를 설명하는 모습이 인상적이었습니다.',
            media: JSON.stringify([]),
            author: '이슬반_김교사',
            followUps: JSON.stringify(['개성있는 창작활동 지원', '작품 전시 기회 제공']),
            linkedToReport: false,
            createdAt: new Date('2025-09-08T14:35:00').toISOString(),
            updatedAt: new Date('2025-09-08T14:35:00').toISOString(),
        },
        {
            childId: 4,
            date: '2025-09-10',
            time: '09:45',
            domain: '자연',
            tags: JSON.stringify(['관찰력', '호기심', '과학적사고']),
            summary: '곤충 관찰 활동에서 세밀한 관찰력과 궁금증을 보이며 질문을 지속적으로 함',
            detail: '원 앞마당에서 곤충 관찰 활동을 하였습니다. 개미집을 발견하고 10분 이상 집중해서 관찰했습니다. "왜 개미들이 줄을 서서 걸어요?", "무거운 것도 들 수 있어요?"라고 연속적으로 질문했습니다. 돋보기로 개미를 자세히 들여다보며 "다리가 6개구나!", "더듬이가 계속 움직여!"라고 발견한 것들을 신나게 공유했습니다. 관찰일지에 개미 그림을 그리며 특징을 기록했습니다.',
            media: JSON.stringify([]),
            author: '이슬반_박교사',
            followUps: JSON.stringify(['자연관찰 활동 확대', '과학적 호기심 지원']),
            linkedToReport: false,
            createdAt: new Date('2025-09-10T10:00:00').toISOString(),
            updatedAt: new Date('2025-09-10T10:00:00').toISOString(),
        },
        {
            childId: 4,
            date: '2025-09-12',
            time: '13:30',
            domain: '전반',
            tags: JSON.stringify(['일상생활', '자립성', '책임감']),
            summary: '점심 후 정리정돈을 스스로 하고 친구들도 도와주는 모습을 보임',
            detail: '점심시간이 끝난 후 자신의 그릇을 정리하고 의자를 제자리에 밀어넣었습니다. 그 후 옆 친구가 흘린 음식을 닦아주며 "괜찮아, 내가 도와줄게"라고 말했습니다. 교사가 칭찬하자 "우리 반이 깨끗해야 기분이 좋아져요"라고 답했습니다. 이후 다른 친구들도 함께 정리를 도와 교실이 빠르게 깨끗해졌습니다.',
            media: JSON.stringify([]),
            author: '이슬반_김교사',
            followUps: JSON.stringify(['리더십 발달 관찰', '책임감 있는 역할 부여']),
            linkedToReport: false,
            createdAt: new Date('2025-09-12T13:45:00').toISOString(),
            updatedAt: new Date('2025-09-12T13:45:00').toISOString(),
        },
        {
            childId: 4,
            date: '2025-09-15',
            time: '10:30',
            domain: '사회',
            tags: JSON.stringify(['갈등해결', '양보', '협상능력']),
            summary: '친구와의 갈등 상황에서 대화를 통해 해결책을 찾아나가는 모습 관찰',
            detail: '자유놀이 시간에 친구와 같은 교구를 사용하고 싶어서 갈등이 발생했습니다. 처음에는 "내가 먼저 가져왔어!"라고 주장했으나, 친구가 속상해하는 것을 보고 "그럼 우리 같이 쓸까?"라고 제안했습니다. 친구가 동의하자 "10분씩 번갈아가면서 하자"라고 구체적인 방법을 제시했습니다. 약속을 지키며 놀이했고, 나중에는 함께 협력하여 더 재미있는 놀이를 만들어냈습니다.',
            media: JSON.stringify([]),
            author: '이슬반_박교사',
            followUps: JSON.stringify(['갈등해결 능력 격려', '협력놀이 기회 확대']),
            linkedToReport: false,
            createdAt: new Date('2025-09-15T10:45:00').toISOString(),
            updatedAt: new Date('2025-09-15T10:45:00').toISOString(),
        },
        {
            childId: 4,
            date: '2025-09-17',
            time: '11:20',
            domain: '신체',
            tags: JSON.stringify(['소근육발달', '집중력', '정교함']),
            summary: '구슬 꿰기 활동에서 끝까지 포기하지 않고 완성하며 정교한 손동작을 보임',
            detail: '소근육 발달을 위한 구슬 꿰기 활동을 하였습니다. 처음에는 구슬이 잘 꿰어지지 않아 frustration을 보였으나, "천천히 해보자"고 스스로 다독이며 계속 시도했습니다. 20분 동안 집중하여 알록달록한 구슬로 목걸이를 완성했습니다. "어려웠지만 예쁘게 나왔어요!"라고 뿌듯해하며 친구들에게 자랑했습니다. 손목 사용과 손가락의 정교함이 이전보다 향상되었습니다.',
            media: JSON.stringify([]),
            author: '이슬반_김교사',
            followUps: JSON.stringify(['소근육 활동 지속 제공', '집중력 향상 활동 계획']),
            linkedToReport: false,
            createdAt: new Date('2025-09-17T11:35:00').toISOString(),
            updatedAt: new Date('2025-09-17T11:35:00').toISOString(),
        },
        {
            childId: 4,
            date: '2025-09-19',
            time: '14:00',
            domain: '의사소통',
            tags: JSON.stringify(['듣기능력', '이해력', '반응성']),
            summary: '교사의 설명을 주의 깊게 듣고 정확하게 이해하여 행동으로 옮기는 모습',
            detail: '새로운 게임 규칙을 설명할 때 다른 친구들보다 집중해서 들었습니다. 복잡한 규칙이었지만 한 번의 설명으로 이해하고, "그럼 이렇게 하는 거예요?"라며 확인 질문을 했습니다. 게임이 시작되자 규칙을 정확히 지켰고, 친구가 헷갈려할 때 "이렇게 하는 거야"라고 친절하게 알려주었습니다. 듣기 능력과 이해력이 또래에 비해 뛰어난 것으로 관찰됩니다.',
            media: JSON.stringify([]),
            author: '이슬반_박교사',
            followUps: JSON.stringify(['복잡한 지시사항 제공', '또래 도우미 역할 부여']),
            linkedToReport: false,
            createdAt: new Date('2025-09-19T14:15:00').toISOString(),
            updatedAt: new Date('2025-09-19T14:15:00').toISOString(),
        },
        {
            childId: 4,
            date: '2025-09-22',
            time: '09:15',
            domain: '예술',
            tags: JSON.stringify(['음악활동', '리듬감각', '표현력']),
            summary: '동요에 맞춰 몸짓 표현을 하며 뛰어난 리듬감과 창의적 동작을 보여줌',
            detail: '음악 시간에 "나뭇잎배" 동요를 부르며 율동을 했습니다. 기본 율동 외에도 자신만의 동작을 추가하여 표현했습니다. 특히 나뭇잎이 물 위에 떠가는 부분에서는 팔을 부드럽게 흔들며 우아하게 표현했습니다. 음악의 빠르기가 변할 때마다 동작의 속도도 적절히 조절했습니다. 다른 친구들도 따라하며 함께 즐거운 시간을 보냈습니다.',
            media: JSON.stringify([]),
            author: '이슬반_김교사',
            followUps: JSON.stringify(['음악 표현활동 확대', '리더 역할 기회 제공']),
            linkedToReport: false,
            createdAt: new Date('2025-09-22T09:30:00').toISOString(),
            updatedAt: new Date('2025-09-22T09:30:00').toISOString(),
        },
        {
            childId: 4,
            date: '2025-09-24',
            time: '10:45',
            domain: '자연',
            tags: JSON.stringify(['식물관찰', '생명존중', '돌봄']),
            summary: '교실 화분의 변화를 세심하게 관찰하고 물주기를 자발적으로 도움',
            detail: '교실 한쪽에 있는 화분을 매일 관찰하며 변화를 기록하고 있습니다. 오늘은 "새 잎이 하나 더 났어요!"라고 신나게 알려주었습니다. 화분의 흙이 마른 것을 보고 "목이 마를 것 같아요. 물을 줄까요?"라고 물어보고 조심스럽게 물을 주었습니다. 물을 줄 때도 "너무 많이 주면 안 되지?" 하며 적당량을 고민하는 모습이 인상적이었습니다.',
            media: JSON.stringify([]),
            author: '이슬반_박교사',
            followUps: JSON.stringify(['식물 돌봄 책임자 역할 부여', '자연관찰 일지 작성']),
            linkedToReport: false,
            createdAt: new Date('2025-09-24T11:00:00').toISOString(),
            updatedAt: new Date('2025-09-24T11:00:00').toISOString(),
        },
        {
            childId: 4,
            date: '2025-09-26',
            time: '13:15',
            domain: '전반',
            tags: JSON.stringify(['문제해결', '독립성', '시도정신']),
            summary: '어려운 퍼즐을 혼자 힘으로 해결하려고 여러 방법을 시도하는 모습',
            detail: '100피스 퍼즐에 도전했습니다. 처음에는 무작정 맞춰보려 했으나 잘 되지 않자, 스스로 전략을 세웠습니다. "먼저 모서리부터 찾아보자"라고 중얼거리며 체계적으로 접근했습니다. 중간에 어려워서 포기하고 싶어했지만, "조금만 더 해보자"라고 자신을 격려하며 30분 동안 집중했습니다. 절반 정도 완성했을 때 너무 기뻐하며 친구들을 불러 보여주었습니다.',
            media: JSON.stringify([]),
            author: '이슬반_김교사',
            followUps: JSON.stringify(['단계별 퍼즐 제공', '문제해결 전략 칭찬']),
            linkedToReport: false,
            createdAt: new Date('2025-09-26T13:30:00').toISOString(),
            updatedAt: new Date('2025-09-26T13:30:00').toISOString(),
        },
        {
            childId: 4,
            date: '2025-09-28',
            time: '11:30',
            domain: '사회',
            tags: JSON.stringify(['배려', '공감능력', '친구관계']),
            summary: '속상해하는 친구를 위로하고 함께 놀이하자고 제안하는 따뜻한 모습',
            detail: '한 친구가 가져온 장난감이 고장나서 울고 있을 때, 다가가서 "괜찮아, 속상하지 마"라고 위로해주었습니다. "우리 다른 재미있는 거 하자"라며 친구의 손을 잡고 블록 코너로 데려갔습니다. 함께 블록으로 자동차를 만들어주며 "이건 새 자동차야, 더 멋지지?"라고 말해주었습니다. 친구가 웃음을 되찾자 함께 기뻐하며 계속 놀이했습니다.',
            media: JSON.stringify([]),
            author: '이슬반_박교사',
            followUps: JSON.stringify(['공감능력 발달 관찰', '친구관계 촉진 활동']),
            linkedToReport: false,
            createdAt: new Date('2025-09-28T11:45:00').toISOString(),
            updatedAt: new Date('2025-09-28T11:45:00').toISOString(),
        },
        {
            childId: 4,
            date: '2025-09-29',
            time: '14:30',
            domain: '신체',
            tags: JSON.stringify(['체력', '지구력', '신체조절']),
            summary: '바깥놀이에서 지속적인 신체활동을 하며 좋은 체력과 활동성을 보임',
            detail: '바깥놀이 시간에 친구들과 술래잡기를 했습니다. 30분 동안 쉬지 않고 뛰어다니며 놀이에 참여했습니다. 술래가 되었을 때도 포기하지 않고 끝까지 친구들을 잡으려고 노력했습니다. "힘들지만 재미있어!"라고 말하며 땀을 흘리면서도 계속 활동했습니다. 놀이 후에도 "더 하고 싶어요"라며 아쉬워했습니다. 체력과 지구력이 또래에 비해 좋은 편입니다.',
            media: JSON.stringify([]),
            author: '이슬반_김교사',
            followUps: JSON.stringify(['다양한 신체활동 제공', '체력증진 프로그램 참여']),
            linkedToReport: false,
            createdAt: new Date('2025-09-29T14:45:00').toISOString(),
            updatedAt: new Date('2025-09-29T14:45:00').toISOString(),
        },
        {
            childId: 4,
            date: '2025-09-30',
            time: '15:00',
            domain: '전반',
            tags: JSON.stringify(['성장', '자신감', '종합발달']),
            summary: '9월 한 달 동안의 성장을 스스로 인식하고 자신감 있게 표현하는 모습',
            detail: '9월 마지막 날, 한 달 동안 했던 활동들을 회상하는 시간을 가졌습니다. "나는 이제 평균대도 혼자 걸을 수 있고, 퍼즐도 어려운 것도 할 수 있어요"라고 자신의 성장을 스스로 평가했습니다. "친구들하고도 더 잘 놀 수 있게 되었어요"라며 사회성 발달도 인식하고 있었습니다. 10월에 하고 싶은 활동들에 대해서도 "새로운 책도 읽고, 더 어려운 만들기도 해보고 싶어요"라고 적극적으로 의견을 표현했습니다.',
            media: JSON.stringify([]),
            author: '이슬반_김교사',
            followUps: JSON.stringify(['전반적 발달 지속 관찰', '10월 개별 목표 설정']),
            linkedToReport: true,
            createdAt: new Date('2025-09-30T15:15:00').toISOString(),
            updatedAt: new Date('2025-09-30T15:15:00').toISOString(),
        }
    ];

    await db.insert(observations).values(sampleObservations);
    
    console.log('✅ Observations seeder completed successfully');
}

main().catch((error) => {
    console.error('❌ Seeder failed:', error);
});